# Generated by Django 4.1.2 on 2022-10-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banner')),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('passenger', models.PositiveIntegerField()),
                ('luggages', models.PositiveIntegerField()),
                ('transmission', models.CharField(max_length=255)),
                ('doors', models.PositiveIntegerField()),
                ('refueling', models.TextField()),
                ('washing', models.TextField()),
                ('smoking', models.TextField()),
                ('included', models.CharField(max_length=255)),
                ('excluded', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product')),
                ('image1', models.ImageField(upload_to='product')),
                ('image2', models.ImageField(upload_to='product')),
                ('image3', models.ImageField(upload_to='product')),
                ('stars', models.PositiveIntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
