# Generated by Django 4.1.2 on 2022-11-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_cartproduct_create_alter_cartproduct_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_by', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=255)),
                ('order_status', models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('Order Cancelled', 'Order Cancelled'), ('Order Completed', 'Order Completed')], default='Order Received', max_length=255)),
                ('discount', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Transfer', 'Transfer'), ('Paystack', 'Paystack')], default='Paystack', max_length=255)),
                ('payment_completed', models.BooleanField(default=False)),
                ('ref', models.CharField(max_length=255)),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
            ],
        ),
    ]
